#if !defined(INCLUDE_ROOTSIGNATURES_INCLUDE_)
#define INCLUDE_ROOTSIGNATURES_INCLUDE_

#define RS_EMPTY \
  "RootFlags ( ALLOW_INPUT_ASSEMBLER_INPUT_LAYOUT )"

#endif  // INCLUDE_ROOTSIGNATURES_INCLUDE_