#if !defined (INCLUDE_TEXTURESEMANTICS_INCLUDE_)
#define INCLUDE_TEXTURESEMANTICS_INCLUDE_
  
#define TEX_DIFFUSE 0
#define TEX_NORMAL 1
#define TEX_SPECULAR 2
#define TEX_ROUGHNESS 3
#define TEX_CUSTOM0 4
#define TEX_CUSTOM1 5
#define TEX_CUSTOM2 6

#endif  // INCLUDE_TEXTURESEMANTICS_INCLUDE_