#pragma once

#if FANCY_ENABLE_DX12

#pragma warning(disable : 26812) // Disable "Prefer enum class over enum"

#include "directx/d3d12.h"
#include <dxgi1_4.h>
#include <d3dcompiler.h>
#include <wrl.h>
#include "directx/dxgiformat.h"
#include "Rendering/RendererPrerequisites.h"

namespace {
  void ASSERT_HRESULT(HRESULT aResult)
  {
    assert(aResult == S_OK);
  }

  #define DX12_READ_STATES (D3D12_RESOURCE_STATE_COMMON | D3D12_RESOURCE_STATE_VERTEX_AND_CONSTANT_BUFFER | D3D12_RESOURCE_STATE_INDEX_BUFFER | D3D12_RESOURCE_STATE_DEPTH_READ |  D3D12_RESOURCE_STATE_NON_PIXEL_SHADER_RESOURCE | D3D12_RESOURCE_STATE_PIXEL_SHADER_RESOURCE | D3D12_RESOURCE_STATE_INDIRECT_ARGUMENT | D3D12_RESOURCE_STATE_COPY_SOURCE | D3D12_RESOURCE_STATE_RESOLVE_SOURCE | D3D12_RESOURCE_STATE_RAYTRACING_ACCELERATION_STRUCTURE)
  #define DX12_WRITE_STATES (D3D12_RESOURCE_STATE_RENDER_TARGET | D3D12_RESOURCE_STATE_DEPTH_WRITE | D3D12_RESOURCE_STATE_UNORDERED_ACCESS | D3D12_RESOURCE_STATE_STREAM_OUT | D3D12_RESOURCE_STATE_COPY_DEST | D3D12_RESOURCE_STATE_RESOLVE_DEST)
}

#endif